version: '2'
services:
  base:
    image: node:12.18-alpine
    volumes:
      - nodemodules:/opt/kubesphere/console/node_modules
      - .:/opt/kubesphere/console
    working_dir: /opt/kubesphere/console

  install:
    extends:
      service: base
    command: yarn

  build:
    extends:
      service: base
    command: yarn build

volumes:
  nodemodules:
    external: true
