kind: ConfigMap
apiVersion: v1
metadata:
  name: cv-console-kubesphere
  namespace: $NAMESPACE
data:
  local_config.yaml: |
    server:
      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis-cluster.cv-console-dev.svc
        password: redis_sugon
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        kubesphere: v3.1.1
        kubernetes: v1.20.8
        openpitrix: v0.3.5
      enableKubeConfig: true