apiVersion: v1
kind: Service
metadata:
  name: cv-console-kubesphere
  namespace: $NAMESPACE
  labels:
    app: cv-console-kubesphere
    tier: frontend
    version: v3.1.1  
spec:
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30881
  selector:
    app: cv-console-kubesphere
    tier: frontend
    version: v3.1.1